SimpleInterest/Models/SI.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SimpleInterest.Models
{
    public class SimpleInterestModel
    {
        [Required(ErrorMessage = "Principal amount is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Principal amount must be greater than zero.")]
        public decimal? Principal { get; set; }
        [Required(ErrorMessage = "Rate of interest is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Rate of interest must be greater than zero.")]
        public decimal? Amount {  get; set; }   //Here Amount refers to Rate
        [Required(ErrorMessage = "Number of years is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Number of years must be at least 1.")]
        public int? Year { get; set; }
        [Required(ErrorMessage = "Simple interest is required.")]
        public decimal? SimpleInterest { get; set; }
    }
}

SimpleInterest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleInterest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SimpleInterest/Controllers/SimpleInterestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SimpleInterest.Models;
namespace SimpleInterest.Controllers
{
    public class SimpleInterestController : Controller
    {
        // GET: SimpleInterest
        public ActionResult DisplaySimpleInterest()
        {
           SimpleInterestModel obj = new SimpleInterestModel();
           return View(obj);
          
        }

        [HttpPost]
        public ActionResult CalculateSimpleInterest(SimpleInterestModel model)
        {
            // Validate the model
            if (!ModelState.IsValid)//It is used to validate Data & handle the errors which is inside Models class.
            {
                // Return the same view with validation errors
                return View("DisplaySimpleInterest", model);
            }

            //Calculate Simple Interst
            model.SimpleInterest = (model.Principal * model.Amount * model.Year) / 100;
            return View("DisplaySimpleInterest", model);//"DisplaySimpleInterest": This explicitly tells ASP.NET MVC which Razor view to render, irrespective of the action method name & in this case it will render DisplaySimpleInterest view.
        }
    }
}

SimpleInterest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

SimpleInterest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

SimpleInterest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

SimpleInterest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*Here @Html.ActionLink refers to create hyperlink of type Home, Index-ActionMethod, Home-ControllerName*@
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        @* All content pages or diffrent View pages will be rendered inside @RenderBody() only *@
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-unobtrusive-ajax/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

</body>
</html>

SimpleInterest/Views/SimpleInterest/DisplaySimpleInterest.cshtml
@model SimpleInterest.Models.SimpleInterestModel

@{ 
    ViewBag.Title = "Simple Interest Calculator";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Or set to `null` if no layout
}

<h2>Simple Interest Calculator</h2>

@using (Html.BeginForm("CalculateSimpleInterest", "SimpleInterest", FormMethod.Post))//It will genearte this html <form action="/SimpleInterest/CalculateSimpleInterest" method="post"> where SimpleInterest is controller name & CalculateSimpleInterest

{
                <div>
                    <label for="Principal">Principal Amount:</label>
                    @Html.TextBoxFor(m => m.Principal, new { @class = "form-control", placeholder = "Enter Principal Amount" })
                    @Html.ValidationMessageFor(m => m.Principal, "", new { @class = "text-danger" })
                    @*<input type="text" name="Principal" id="Principal" min=0/>*@
                </div>
                <div>
                    <label for="Amount">Rate: </label>
                    @Html.TextBoxFor(m => m.Amount, new { @class = "form-control", placeholder = "Enter rate Amount" })
                    @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                </div>
                <div>
                    <label for="Year">Time:</label>
                    @Html.TextBoxFor(m => m.Year, new { @class = "form-control", placeholder = "Enter time period" })
                    @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                </div>
                <div>
                    <button type="submit" class= "btn btn-primary">Submit</button>
                </div>

                if (Model.SimpleInterest > 0)
                {
                    <h3>Result:</h3>
                    <p>Simple Interest: <strong>@Model.SimpleInterest</strong></p>
                }
}